name: Deploy Dockerized Node.js App to Azure

on:
  push:
    branches:
      - main  # ou 'master' selon ton repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE1}}

      - name: Build Docker image
        run: |
          docker build -t visit-counter-app .

      - name: Zip Docker image
        run: |
          zip -r release.zip .

      - name: Deploy to Azure Web App (Docker)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cloud-docker-app1'  # Nom exact de ton App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
